Avoid unlocking NULL
When `options(install.lock = FALSE)` is set in `.Rprofile`, an error will be thrown when a package is successfully installed, aborting the installation of other packages.

```
Error:                                           
! error in pak subprocess
Caused by error in `filelock::unlock(lockfile)`:
! `unlock()` needs a lock object, not a file name
```

Add a NULL check to prevent this behavior.